import Foundation

/// Teaches the user's shell to announce where commands start and end.
///
/// Exit status is not observable from outside: the command is the shell's
/// child, not ours, so `wait` is unavailable to us and no kernel interface will
/// hand over a non-child's exit code. The shell has to say so itself, which is
/// what OSC 133 is for — `C` on start, `D;<status>` on finish.
///
/// Majora supplies that by pointing `ZDOTDIR` at a small generated config that
/// sources the user's own files first and then installs two hooks. The user's
/// `ZDOTDIR` is restored before their prompt runs, so their configuration sees
/// what it expects.
public enum ShellIntegration {

    /// Environment for a shell, with integration installed where supported.
    ///
    /// Integration is a nicety, not a requirement: if anything fails the base
    /// environment is returned unchanged and Majora falls back to detecting a
    /// busy terminal from its foreground process.
    public static func environment(
        forShell shellPath: String,
        base: [String: String] = ProcessInfo.processInfo.environment,
        supportDirectory: URL? = nil
    ) -> [String: String] {
        guard shellPath.hasSuffix("zsh") else { return base }
        guard let directory = try? installZsh(in: supportDirectory) else { return base }

        var environment = base
        environment["MAJORA_USER_ZDOTDIR"] = base["ZDOTDIR"] ?? base["HOME"]
            ?? FileManager.default.homeDirectoryForCurrentUser.path
        environment["ZDOTDIR"] = directory.path
        return environment
    }

    /// Where the generated zsh config lives.
    public static func defaultSupportDirectory() -> URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        return base
            .appendingPathComponent("Majora", isDirectory: true)
            .appendingPathComponent("shell-integration/zsh", isDirectory: true)
    }

    @discardableResult
    static func installZsh(in supportDirectory: URL?) throws -> URL {
        let directory = supportDirectory ?? defaultSupportDirectory()
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        for (name, contents) in zshFiles {
            let url = directory.appendingPathComponent(name)
            // Rewritten every launch so an upgraded Majora cannot be shadowed
            // by a stale snippet.
            try contents.write(to: url, atomically: true, encoding: .utf8)
        }
        return directory
    }

    /// Sources the user's equivalent file, keeping `ZDOTDIR` pointed here so
    /// the rest of the startup sequence still finds our files.
    private static func forwarding(to name: String) -> String {
        """
        # Generated by Majora. Sources your own \(name), then continues.
        if [[ -z "$MAJORA_USER_ZDOTDIR" ]]; then
          MAJORA_USER_ZDOTDIR="$HOME"
        fi
        _majora_ours="$ZDOTDIR"
        [[ -f "$MAJORA_USER_ZDOTDIR/\(name)" ]] && source "$MAJORA_USER_ZDOTDIR/\(name)"
        # Your config may set ZDOTDIR itself; honour it, but keep reading ours
        # for the rest of startup.
        if [[ "$ZDOTDIR" != "$_majora_ours" ]]; then
          MAJORA_USER_ZDOTDIR="$ZDOTDIR"
          ZDOTDIR="$_majora_ours"
        fi
        unset _majora_ours

        """
    }

    static var zshFiles: [String: String] {
        [
            ".zshenv": forwarding(to: ".zshenv"),
            ".zprofile": forwarding(to: ".zprofile"),
            ".zlogin": forwarding(to: ".zlogin"),
            ".zshrc": forwarding(to: ".zshrc") + """
            # Report command boundaries so Majora can show whether a tab is busy
            # and whether the last command succeeded.
            autoload -Uz add-zsh-hook 2>/dev/null || return 0
            typeset -g _majora_active=0

            _majora_preexec() {
              _majora_active=1
              printf '\\e]133;C\\a'
            }

            _majora_precmd() {
              local ret=$?
              if (( _majora_active )); then
                printf '\\e]133;D;%s\\a' "$ret"
                _majora_active=0
              fi
            }

            add-zsh-hook preexec _majora_preexec
            add-zsh-hook precmd _majora_precmd

            # Hand the shell back to the user's own configuration.
            ZDOTDIR="$MAJORA_USER_ZDOTDIR"

            """
        ]
    }
}
